# Name of the automation
name: Hourly HR Reply Processing

# Controls when the workflow will run
on:
  # Runs on a schedule (cron job)
  schedule:
    # This runs at the beginning of every hour
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This job processes email replies
  process-replies:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Sets up python for use in actions
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Creates the credentials file from the GitHub Secret
      - name: Create Credentials File
        run: echo "${{ secrets.GCP_SA_KEY }}" > creds.json

      # Installs the python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs the reply processing script
      - name: Run the reply processing script
        run: python process_replies.py
