# Name of the automation
name: Daily HR Schedule Run

# Controls when the workflow will run
on:
  # Runs on a schedule (cron job)
  schedule:
    # This is for 17:00 CEST (15:00 UTC) every day
    - cron: '0 15 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Sets up python for use in actions
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Creates the credentials file from the GitHub Secret
      - name: Create Credentials File
        run: echo "${{ secrets.GCP_SA_KEY }}" > creds.json

      # Installs the python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Runs the main python script
      - name: Run the scheduling script
        run: python scheduler.py
